//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2018_Desafio_CSharp_Token_Lab.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDTokenLabEntities : DbContext
    {
        public BDTokenLabEntities()
            : base("name=BDTokenLabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EventoEntity> Eventos { get; set; }
        public virtual DbSet<UsuarioEntity> Usuarios { get; set; }
    }
}
