//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2018_Desafio_CSharp_Token_Lab.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventoEntity
    {
        public int Id { get; set; }
        public System.DateTime Data { get; set; }
        public System.TimeSpan Inicio { get; set; }
        public System.TimeSpan Fim { get; set; }
        public string Descricao { get; set; }
    
        public virtual UsuarioEntity Usuarios { get; set; }
    }
}
